[package]
name = "corp_one_bevy_game"
version = "0.1.0"
authors = ["marko.lazic <markolazic@protonmail.com>"]
edition = "2018"

[workspace]
members = [
    "crates/*"
]

[dependencies]
bevy = "0.2.1"

# Local
corp-metrics = { path = "crates/corp-metrics", version = "0.1.0" }
corp-console = { path = "crates/corp-console", version = "0.1.0" }
corp-scene = { path = "crates/corp-scene", version = "0.1.0" }
corp-input = { path = "crates/corp-input", version = "0.1.0" }