[workspace]
resolver = "2"

members = [
    "corp_client",
    "corp_server",
    "corp_shared",
    "tests",
]
default-members = [
    "corp_client",
    "corp_server",
    "corp_shared",
    "tests",
]