[package]
name = "corp_one"
version = "0.1.0"
authors = ["marko.lazic <markolazic@protonmail.com>"]
edition = "2018"

[workspace]
members = [
    "corp_tests",
]

[dependencies]
bevy = "0.4.0"
kurinji = "1.0.5"