[workspace]
resolver = "2"

exclude = [
    "benches",
]
members = [
    "corp_client",
    "corp_server",
    "corp_shared",
    "tools/ci",
]
default-members = [
    "corp_client",
    "corp_server",
    "corp_shared",
]

[workspace.dependencies]
bevy = { version = "0.14.1", default-features = false }


