[workspace]
resolver = "2"

exclude = [
    "benches",
]
members = [
    "corp_client",
    "corp_server",
    "corp_shared",
    "tools/ci",
]
default-members = [
    "corp_client",
    "corp_server",
    "corp_shared",
]

[workspace.dependencies]
bevy = { version = "0.15.0", default-features = false }
lightyear = { version = "0.18.0", default-features = false }
serde = { version = "1", default-features = false }
avian3d = { version = "0.2.0", default-features = false }
rand = "0.8.5"

