[workspace]
resolver = "2"

exclude = [
    "benches",
]
members = [
    "corp_client",
    "corp_server",
    "corp_shared",
    "tests",
    "tools/ci",
]
default-members = [
    "corp_client",
    "corp_server",
    "corp_shared",
    "tests",
]