[unstable] # Enable cranelift
codegen-backend = true # Enable cranelift

# Enable a small amount of optimization in dev mode
[profile.dev]
opt-level = 0
debug = true
incremental = true

codegen-backend = "cranelift"  # Enable cranelift

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
codegen-backend = "llvm"   # Enable cranelift
opt-level = 3

[profile.debugging]
inherits = "dev"
opt-level = 0
debug = true

# Enable high optimizations for our code in release mode, slower compile times
[profile.release]
codegen-units = 1

[build]
rustc-wrapper = "/opt/homebrew/bin/sccache"
rustflags = ["-Z", "share-generics=y", "-C", "debuginfo=2"]

[env]
RUST_BACKTRACE = "1"
RUSTFLAGS = "-Zthreads=8"

[term]
color = "always"