[package]
name = "corp_client"
version = "0.1.0"
authors = ["marko.lazic <markolazic@protonmail.com>"]
edition = "2021"

[dependencies]
corp_shared = { path = "../corp_shared" }
bevy = { workspace = true, features = ["bevy_asset", "bevy_ui", "bevy_text", "animation", "tonemapping_luts", "bevy_animation", "bevy_winit", "dynamic_linking", "png", "bevy_gltf"] }
log = { version = "*", features = ["max_level_debug", "release_max_level_warn"] }
leafwing-input-manager = { version = "0.15.1" }
bevy_mod_picking = { version = "0.20.1", default-features = false, features = ["backend_avian"] }
bevy-inspector-egui = "0.27.0"
bevy_asset_loader = { version = "0.21.0", default-features = false, features = ["3d"] }
bevy_kira_audio = { version = "0.20.0", default-features = false, features = ["wav", "ogg"] }
bevy_common_assets = { version = "0.11.0", features = ["ron"] }
avian3d = { version = "0.1.2" }
bevy-tnua = "0.20.0"
bevy-tnua-avian3d = "0.1.1"
bevy_dolly = { path = "../../bevy_dolly", version = "0.0.4", default-features = false, features = ["drivers"] }
bevy-scene-hook = { path = "../../bevy-scene-hook", version = "11.0.0" }
bevy_framepace = "0.17.1"
serde = "1.0.203"
rand = "0.8.5"
bitflags = "2.4"

[dev-dependencies]
bevy_panorbit_camera = "0.20.0"
lazy_static = "1.4.0"
derive_more = "1.0.0"
approx = "0.5"
glam = { version = "0.29.2", features = ["approx"] }


[[example]]
name = "transforms"
path = "examples/transforms.rs"

[[example]]
name = "vector_bullet"
path = "examples/vector_bullet.rs"

[[example]]
name = "animation"
path = "examples/animation.rs"

[[example]]
name = "barrier"
path = "examples/shader/barrier.rs"

[[example]]
name = "distortion"
path = "examples/shader/distortion.rs"

[[example]]
name = "force_field"
path = "examples/shader/force_field.rs"

[[example]]
name = "state"
path = "examples/state/state.rs"

[[example]]
name = "observer"
path = "examples/observer.rs"
