[package]
name = "corp_client"
version = "0.1.0"
authors = ["marko.lazic <markolazic@protonmail.com>"]
edition = "2021"

[features]
default = [
    "bevy_kira_audio/wav"
]

[dependencies]
corp_shared = { path = "../corp_shared" }
rand = "0.8.5"
bevy = { version = "0.7.0", features = ["wav"] }
bevy_framepace = "0.4.0"
bevy_mod_raycast = "0.4.0"
bevy_mod_picking = "0.6.1"
bevy_transform_gizmo = "0.2.1"
bevy_prototype_debug_lines = { version = "0.7.1" }
bevy_mouse_tracking_plugin = "0.2.1"
bevy_prototype_lyon = "0.5.0"
blender_bevy_toolkit = { path = "../../blender_bevy_toolkit" }
bevy-inspector-egui = "0.11.0"
bevy_asset_loader = "0.10.0"
bevy_kira_audio = "0.10.0"
bevy_asset_ron = "0.4.0"
bevy_input_actionmap = { git = "https://github.com/lightsoutgames/bevy_input_actionmap.git", branch = "main" }
heron = { version = "3.1.0", features = ["3d"] }
glam = "0.20.5"
serde = "1.0.137"

[[example]]
name = "transforms"
path = "examples/transforms.rs"

[[example]]
name = "look"
path = "examples/look.rs"

[[example]]
name = "look_trigger"
path = "examples/look_trigger.rs"

[[example]]
name = "vector_bullet"
path = "examples/vector_bullet.rs"

[[example]]
name = "radial_trigger"
path = "examples/radial_trigger.rs"


[[example]]
name = "local_to_world"
path = "examples/local_to_world.rs"