[package]
name = "corp_client"
version = "0.1.0"
authors = ["marko.lazic <markolazic@protonmail.com>"]
edition = "2021"

[dependencies]
corp_shared = { path = "../corp_shared" }
bevy = { workspace = true, features = ["wav"] }
leafwing-input-manager = "0.14.0"
bevy_mod_picking = { version = "0.20.0", default-features = false, features = ["backend_rapier"] }
bevy-inspector-egui = "0.25.0"
bevy_asset_loader = "0.21.0"
bevy_kira_audio = { version = "0.20.0", features = ["wav", "ogg"] }
bevy_common_assets = { version = "0.11.0", features = ["ron"] }
bevy_rapier3d = "0.27.0"
bevy_dolly = "0.0.4"
bevy-scene-hook = { path = "../../bevy-scene-hook", version = "11.0.0" }
bevy_framepace = "0.17.1"
serde = "1.0.197"
rand = "0.8.5"
bitflags = "2.4"

[dev-dependencies]
bevy_panorbit_camera = "0.19.1"
lazy_static = "1.4.0"
derive_more = "0.99.17"
approx = "0.5"
glam = { version = "0.27.0", features = ["approx"] }


[[example]]
name = "transforms"
path = "examples/transforms.rs"

[[example]]
name = "vector_bullet"
path = "examples/vector_bullet.rs"

[[example]]
name = "animation"
path = "examples/animation.rs"

[[example]]
name = "barrier"
path = "examples/shader/barrier.rs"

[[example]]
name = "distortion"
path = "examples/shader/distortion.rs"

[[example]]
name = "force_field"
path = "examples/shader/force_field.rs"

[[example]]
name = "state"
path = "examples/state/state.rs"

[[example]]
name = "observer"
path = "examples/observer.rs"