[package]
name = "corp_client"
version = "0.1.0"
authors = ["marko.lazic <markolazic@protonmail.com>"]
edition = "2021"

[dependencies]
corp_shared = { path = "../corp_shared" }
bevy = { workspace = true, features = ["wav"] }
leafwing-input-manager = "0.12.1"
bevy_mod_picking = { version = "0.17.0", default-features = false, features = ["backend_rapier"] }
bevy-inspector-egui = "0.21.0"
bevy_asset_loader = "0.18.0"
bevy_kira_audio = { version = "0.18.0", features = ["wav", "ogg"] }
bevy_common_assets = { version = "0.8.0", features = ["ron"] }
bevy_rapier3d = "0.23.0"
bevy_dolly = "0.0.2"
bevy-scene-hook = "9.0.0"
serde = "1.0.192"
rand = "0.8.5"
bitflags = "2.4"
bevy_framepace = "0.14.1"

[dev-dependencies]
bevy_prototype_debug_lines = { version = "0.11.1" }
bevy_prototype_lyon = "0.10.0"
bevy_panorbit_camera = "0.9.0"
lazy_static = "1.4.0"
derive_more = "0.99.17"
approx = "0.5"
glam = { version = "0.24", features = ["approx"] }


[[example]]
name = "transforms"
path = "examples/transforms.rs"

[[example]]
name = "look_trigger"
path = "examples/look_trigger.rs"

[[example]]
name = "vector_bullet"
path = "examples/vector_bullet.rs"

[[example]]
name = "radial_trigger"
path = "examples/radial_trigger.rs"

[[example]]
name = "local_to_world"
path = "examples/local_to_world.rs"

[[example]]
name = "animation"
path = "examples/animation.rs"

[[example]]
name = "barrier"
path = "examples/shader/barrier.rs"

[[example]]
name = "distortion"
path = "examples/shader/distortion.rs"

[[example]]
name = "starfield"
path = "examples/shader/starfield.rs"

[[example]]
name = "clamp"
path = "examples/transform/clamp.rs"

[[example]]
name = "state"
path = "examples/state/state.rs"

[[example]]
name = "pick"
path = "examples/pick.rs"
