[package]
name = "corp_client"
version = "0.1.0"
authors = ["marko.lazic <markolazic@protonmail.com>"]
edition = "2021"

[dependencies]
corp_shared = { path = "../corp_shared" }
bevy = { version = "0.10.1", features = ["wav"] }
leafwing-input-manager = "0.9.2"
bevy_mod_raycast = "0.8.0"
bevy_mod_picking = { version = "0.13.0", default-features = false, features = ["backend_rapier"] }
bevy-inspector-egui = "0.18.3"
bevy_asset_loader = { version = "0.16.0" }
bevy_kira_audio = "0.15.0"
bevy_common_assets = { version = "0.6.0", features = ["ron"] }
bevy_rapier3d = "0.21.0"
bevy_dolly = { path = "../../bevy_dolly" }
bevy-scene-hook = "6.0.0"
bevy-trait-query = "0.2.1"
glam = "0.24.0"
serde = "1.0.145"
rand = "0.8.5"
bitflags = "2.2.1"

[dev-dependencies]
bevy_prototype_debug_lines = { version = "0.10.0" }
impl-tools = "0.8.0"
bevy_prototype_lyon = "0.8.0"
lazy_static = "1.4.0"
derive_more = "0.99.17"
float_eq = "1.0.1"

[[example]]
name = "transforms"
path = "examples/transforms.rs"

[[example]]
name = "look_trigger"
path = "examples/look_trigger.rs"

[[example]]
name = "vector_bullet"
path = "examples/vector_bullet.rs"

[[example]]
name = "radial_trigger"
path = "examples/radial_trigger.rs"

[[example]]
name = "local_to_world"
path = "examples/local_to_world.rs"

[[example]]
name = "animation"
path = "examples/animation.rs"

[[example]]
name = "barrier"
path = "examples/shader/barrier.rs"

[[example]]
name = "clamp"
path = "examples/transform/clamp.rs"

[[example]]
name = "state"
path = "examples/state/state.rs"

[[example]]
name = "pick"
path = "examples/pick.rs"

[[example]]
name = "ccc"
path = "examples/ccc/ccc.rs"
