[package]
name = "corp_client"
version = "0.1.0"
authors = ["marko.lazic <markolazic@protonmail.com>"]
edition = "2021"

[features]
default = [
    "bevy_kira_audio/wav"
]

[dependencies]
corp_shared = { path = "../corp_shared" }
bevy = { version = "0.8.1", features = ["wav"] }
leafwing-input-manager = "0.5.2"
iyes_loopless = "0.7.1"
bevy_mod_raycast = "0.6.2"
bevy_mod_picking = "0.9.0"
bevy-inspector-egui = "0.13.0"
bevy_asset_loader = { version = "0.12.1", features = ["stageless"] }
bevy_kira_audio = "0.12.0"
bevy_common_assets = { version = "0.3.0", features = ["ron"] }
bevy_rapier3d = { version = "0.17.0", features = ["simd-stable"] }
bevy-scene-hook = "4.1.0"
glam = "0.21.3"
serde = "1.0.145"
rand = "0.8.5"
bitflags = "1.3.2"

[dev-dependencies]
# Examples dependecies
bevy_mouse_tracking_plugin = "0.4.0"
bevy_transform_gizmo = "0.3.3"
bevy_prototype_debug_lines = { version = "0.8.1" }
impl-tools = "0.5.2"
bevy_prototype_lyon = "0.6.0"


[[example]]
name = "transforms"
path = "examples/transforms.rs"

[[example]]
name = "look_trigger"
path = "examples/look_trigger.rs"

[[example]]
name = "vector_bullet"
path = "examples/vector_bullet.rs"

[[example]]
name = "radial_trigger"
path = "examples/radial_trigger.rs"


[[example]]
name = "local_to_world"
path = "examples/local_to_world.rs"

[[example]]
name = "animation"
path = "examples/animation.rs"

[[example]]
name = "barrier"
path = "examples/shader/barrier.rs"