[package]
name = "corp_client"
version = "0.1.0"
authors = ["marko.lazic <markolazic@protonmail.com>"]
edition = "2021"

[features]
default = [
    "bevy_kira_audio/wav"
]

[dependencies]
corp_shared = { path = "../corp_shared" }
bevy = { version = "0.7.0", features = ["wav"] }
leafwing-input-manager = "0.4.1"
iyes_loopless = "0.6.1"
bevy_mod_raycast = "0.5.0"
bevy_mod_picking = "0.7.0"
bevy_prototype_lyon = "0.5.0"
bevy-inspector-egui = "0.11.0"
bevy_asset_loader = { git = "https://github.com/NiklasEi/bevy_asset_loader.git", branch = "main", features = ["stageless"] }
bevy_kira_audio = "0.10.0"
bevy_asset_ron = "0.4.0"
bevy_rapier3d = { version = "0.15.0", features = ["simd-stable"] }
glam = "0.20.5"
serde = "1.0.137"
rand = "0.8.5"
bitflags = "1.3.2"

# Examples dependecies
bevy_mouse_tracking_plugin = "0.2.1"
bevy_transform_gizmo = "0.2.1"
bevy_prototype_debug_lines = { version = "0.7.2" }
impl-tools = "0.3.2"

# Should deprecate
blender_bevy_toolkit = { path = "../../blender_bevy_toolkit" }

[[example]]
name = "transforms"
path = "examples/transforms.rs"

[[example]]
name = "look_trigger"
path = "examples/look_trigger.rs"

[[example]]
name = "vector_bullet"
path = "examples/vector_bullet.rs"

[[example]]
name = "radial_trigger"
path = "examples/radial_trigger.rs"


[[example]]
name = "local_to_world"
path = "examples/local_to_world.rs"

[[example]]
name = "animation"
path = "examples/animation.rs"