[package]
name = "corp_server"
version = "0.1.0"
authors = ["Marko Lazić <marko.lazic@comyno.com>"]
edition = "2018"

[dependencies]
corp_shared = { path = "../corp_shared" }
bevy = "0.5"
bevy_networking_turbulence = "0.3.2"