[package]
name = "corp_server"
version = "0.1.0"
authors = ["Marko Lazić <marko.lazic@comyno.com>"]
edition = "2021"

[dependencies]
corp_shared = { path = "../corp_shared" }
bevy = { workspace = true, features = ["bevy_state", "bevy_color", "async-io", "multi_threaded", "serialize"] }
serde = { version = "1", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
sqlx = { version = "0.8", features = ["runtime-async-std", "sqlite", "chrono"] }
directories = "5.0.1"
