[package]
name = "corp_server"
version = "0.1.0"
authors = ["Marko Lazić <marko.lazic@comyno.com>"]
edition = "2021"

[dependencies]
corp_shared = { path = "../corp_shared" }
bevy_app = { version = "0.11.2", default_features = false }
bevy_core = { version = "0.11.2", default_features = false }
bevy_ecs = { version = "0.11.2", default_features = false }
bevy_time = { version = "0.11.2", default_features = false }
bevy_log = { version = "0.11.2", default_features = false }
bevy-tokio-tasks = "0.11.0"
surrealdb = { version = "1.0.0-beta.9", features = ["kv-mem"] }
once_cell = "1.18.0"
serde = "1.0.183"