[package]
name = "corp_server"
version = "0.1.0"
authors = ["Marko Lazić <marko.lazic@comyno.com>"]
edition = "2021"

[dependencies]
corp_shared = { path = "../corp_shared" }
bevy = { workspace = true }
bevy-tokio-tasks = { git = "https://github.com/EkardNT/bevy-tokio-tasks.git", rev = "215f1e3" }
surrealdb = { version = "1.2.2", features = ["kv-mem"] }
surrealdb-migrations = { git = "https://github.com/johansmitsnl/surrealdb-migrations.git", rev = "db63c07" }
once_cell = "1.19.0"
serde = "1.0.203"
dotenv = "0.15.0"
